# Generated by Django 4.1.2 on 2023-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
