# Generated by Django 4.1.2 on 2023-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_app", "0002_alter_userdetails_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="cropdetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=30)),
                ("nitrogen", models.CharField(max_length=30)),
                ("phosphorous", models.CharField(max_length=30)),
                ("potassium", models.CharField(max_length=30)),
                ("crop_predict", models.CharField(max_length=30)),
                ("fertilize_predict", models.CharField(max_length=30)),
            ],
        ),
    ]
