# Generated by Django 4.1.2 on 2023-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_app", "0003_cropdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="expertadvice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=30)),
                ("Questionname", models.CharField(max_length=50)),
                ("advices", models.CharField(max_length=50)),
                ("todaydate", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="pestdetect",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=30)),
                ("imagename", models.CharField(max_length=50)),
                ("pestname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="rentingtool",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=30)),
                ("toolname", models.CharField(max_length=50)),
                ("toolcost", models.CharField(max_length=50)),
                ("todaydate", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="weatherreport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=30)),
                ("locationname", models.CharField(max_length=50)),
                ("temp", models.CharField(max_length=50)),
                ("todaydate", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
            ],
        ),
    ]
