# Generated by Django 4.1.2 on 2023-02-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crop_app", "0004_expertadvice_pestdetect_rentingtool_weatherreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherreport",
            name="description",
        ),
    ]
